# Generated by Django 5.2.17 on 2026-09-13 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('master-degree', "Master's Degree"), ('bachelor-degree', "Bachelor's Degree"), ('senior-highschool', 'Senior High School'), ('junior-highschool', 'Junior High School'), ('elementary', 'Elementary School')], default='bachelor-degree', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_year', models.PositiveIntegerField()),
                ('ended_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('study', 'Study')], default='full-time', max_length=20),
        ),
    ]
